language: android
jdk: oraclejdk7

before_install:
  - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew assembleRelease

deploy:
  provider: releases
  api_key: GITHUB_TOKEN
  file: app/build/outputs/aar/app-release-0.2.aar
  skip_cleanup: true
  on:
    tags: true