language: android
jdk: oraclejdk7

before_install:
  - chmod +x gradlew

android:
  compileSdk: 21
  buildTools: 22.0.1
  acceptAllLicenses: true

  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

script:
  - ./gradlew assembleDebug