language: android
jdk: oraclejdk7

before_install:
  - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    - build-tools-22.0.1
    - android-22

script:
  - ./gradlew assembleDebug